project:
  type: website

website:
  title: "AEIS wiki"
  navbar:
    logo: imgs/logo.png
    left:
      - href: induction.qmd
      - href: data.qmd
      - href: tools.qmd
      - href: papers.qmd
      - href: writing.qmd
      - href: courses.qmd
      - href: sustainability.qmd
      - href: group-meetings.qmd
      - href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css:
      - styles.css
      - courses.css
    toc: true

bibliography: references.bib